apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      serviceAccountName: myapp
      securityContext:              # ✅ Pod-level securityContext
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: home
          image: docdon0007/homeapi
          ports:
            - containerPort: 3000   # ✅ container field
          resources:                # ✅ container field
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:          # ✅ Container-level securityContext
            privileged: false
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
